---
- name: Common playbook
  hosts: 
    - ubuntu
  gather_facts: yes

  vars:
    apt_packages: 
      - htop
      - vim
      - php8.2
      - kazam
      - filezilla
      - bluefish
    bg_image_url: https://cdn.wallpapersafari.com/55/73/ghY4rc.jpg
    bg_image_dest: "{{ ansible_user_dir }}/Pictures/bg.jpg"
    servers: 
      - galaxy
      - vulcan
      - ameros


  tasks:







