---
# tasks file for dev
- name: Install mandatory packages
  become: yes
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    update_cache: yes
    state: present

- name: Add docker repo
  block:
    - name: Create a directory if it does not exist
      become: yes
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
    
    # - name: Get GPG key
    #   ansible.builtin.get_url:
    #     url: https://download.docker.com/linux/ubuntu/gpg
    #     dest: /etc/apt/keyrings/docker.gpg
    - name: Add apt sign key
      become: yes
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /etc/apt/keyrings/docker.gpg
        state: present

    - name: Get architecture
      shell: dpkg --print-architecture
      register: arch_result

    - name: Add repo
      become: yes
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ arch_result.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        filename: docker
        state: present

- name: Install docker + docker-compose + git
  become: yes
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - docker-compose
      - git
    update_cache: yes
    state: present